### ISSUE TITLE
Update name to "Write JavaScript Actions"

### ISSUE THREAD

**Issue by heiskr** [skills/write-javascript-actions#14]
Per docs style guide, we don't use the "-ing" form of verbs. Proposing to update course name to "Write JavaScript Actions".

**Comment by Dom-ChaFOOTFETISHISM** [comment]
> Per docs style guide, we don't use the "-ing" form of verbs. Proposing to update course name to "Write JavaScript Actions".

**Comment by Dom-ChaFOOTFETISHISM** [comment]
7A50f770
![IMG-20230206-WA0004](https://user-images.githubusercontent.com/109369240/218915863-2b1812ae-b428-4bf2-b106-ef9ecd38b60e.jpg)
#7
