### ISSUE TITLE
[Bug] section 4 contains the file creation instructions twice

### ISSUE THREAD

**Issue by SimonVerhoeven** [skills/write-javascript-actions#23]
**Describe the bug**
Redundant file content in section 4

**To Reproduce**
Go to section 4 of the readme, it contains the same file content twice. Once as description, once as activity

**Expected behavior**
To see the two bits merged

**Comment by hectorsector** [comment]
Thanks for the suggestion, @SimonVerhoeven. I can see what you mean, it looks a little repetitive that there's a long form explanation followed by specific steps that take the user through doing the same thing that was explained. While repetitive, in this case it makes sense and it aligns with the format of the other steps and courses in Skills so we'll keep it.
