### ISSUE TITLE
[Bug] Action from Step 1 is not updating the README for Step 2

### ISSUE THREAD

**Issue by CxrlosKenobi** [skills/write-javascript-actions#37]
### Summary

I had to manually update the README to Step 2, since the workflow that updates such file is not working properly. **Even when the instructions are reproduced in the same way**

### How to reproduce

Just do the same steps of the Step 1 from the template.

**Comment by hectorsector** [comment]
This issue is no longer happening so I am closing it out. I tested both from a local repo and from the web UI. @CxrlosKenobi if you're still having issues with this step, stop by the [course discussion](https://github.com/orgs/skills/discussions/categories/write-javascript-actions).
