### ISSUE TITLE
[Maint] Update Checkout Action Version

### ISSUE THREAD

**Issue by bharatr21** [skills/write-javascript-actions#49]
### Summary
In Step 5, the checkout action still references an old version `actions/checkout@v3` -> Should be updated to `actions/checkout@v4`
![GHActions2](https://github.com/user-attachments/assets/3779e215-8965-4be1-9f19-61034ffd203d)

**Comment by nguyenalex836** [comment]
@bharatr21 Thank you for raising this issue and linking your PR! ✨ I'll triage this for the team to review
